name: Deployment (ECR, Lambda)
on:
  workflow_dispatch:  # manual triggering
    inputs:
      environment:
        type: choice
        description: Environment to deploy to
        options:
        - demo
        - staging
        - prod

env:
  DEPLOYMENT_ENV: ${{ github.event.inputs.environment || 'demo' }}
  REGISTRY: ${{ secrets.ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
  APP_IMAGE: react-usereducer-django-template
  AWS_REGION: us-east-1

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Application image to ECR
      env:
        REMOTE_IMAGE: ${{ env.REGISTRY }}/${{ env.APP_IMAGE }}
        IMAGE_TAG: ${{ github.sha }}
        DEPLOYMENT_ENV: ${{ env.DEPLOYMENT_ENV }}
      run: |
        docker build -f backend/Dockerfile -t $REMOTE_IMAGE:$IMAGE_TAG \
           --build-arg ENV="${DEPLOYMENT_ENV}" .
        docker tag $REMOTE_IMAGE:$IMAGE_TAG $REMOTE_IMAGE:latest
        docker push --all-tags $REMOTE_IMAGE

    - name: Update Lambda
      if: success()
      env:
        DEPLOYMENT_ENV: ${{ env.DEPLOYMENT_ENV }}
        REMOTE_IMAGE: ${{ env.REGISTRY }}/${{ env.APP_IMAGE }}
        REGION: ${{ env.AWS_REGION }}
        FUNC_NAME: ${{ env.DEPLOYMENT_ENV }}-${{ env.APP_IMAGE }}
      run: |
        aws lambda update-function-code \
          --function-name $FUNC_NAME \
          --region $REGION \
          --image-uri $REMOTE_IMAGE:latest
